services:
  - type: web
    name: lapro-solutions
    env: node
    buildCommand: npm install
    startCommand: npm start
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
